
server:
  port: 8888
spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: file:///C:/Users/Gui e Di/Documents/Project/micro-services-dio/config-master